include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_final_locals: true
    avoid_unused_constructor_parameters: true
    use_super_parameters: true
    always_use_package_imports: false
    unnecessary_this: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
